workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ "/^dependabot-.*/"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

.base-cargo:
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo

.base-frontend-cache:
  image:
    name: registry.ulbricht.casa/docker-images/leptos-docker-base-image:latest
    pull_policy: always
  extends:
    - .base-cargo
  variables:
    CARGO_PROFILE_RELEASE_PANIC: abort
    CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
    CARGO_PROFILE_RELEASE_OPT_LEVEL: z
    CARGO_PROFILE_RELEASE_DEBUG: "false"
    CARGO_PROFILE_RELEASE_LTO: "true"
    CARGO_PROFILE_RELEASE_STRIP: "symbols"
  cache:
    key: $CI_PROJECT_NAME-leptos
    paths:
      - $CI_PROJECT_DIR/target/
      - $CI_PROJECT_DIR/.cargo/
      - $CI_PROJECT_DIR/Cargo.lock

.base-docker:
  image: registry.ulbricht.casa/docker-images/buildah:latest
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$DOCKERHUB_PASSWORD" | buildah login -u "$DOCKERHUB_USER" --password-stdin docker.io

.base-docker-build:
  extends: .base-docker
  stage: docker
  variables:
    TAG: test
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$APP/$ARCH:$TAG
  script:
    - buildah build --platform=linux/$ARCH --build-arg "APP=crafting-web" --build-arg "PKG_DIR=crafting/pkg" -f "$CI_PROJECT_DIR/docker/Dockerfile" -t $IMAGE_TAG $CI_PROJECT_DIR/$ARCH
    - "[[ -z '$NO_PUSH' ]] || buildah push $IMAGE_TAG"
  parallel:
    matrix:
      - ARCH:
          - amd64
          - arm64
  tags:
    - runner-${ARCH}

.base-merge-manifests:
  stage: deploy
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [ "" ]
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$APP
    IMAGE_TAG: $IMAGE:$TAG
  script:
    - buildah manifest create $IMAGE_TAG
    - buildah manifest add $IMAGE_TAG docker://$IMAGE/amd64:$TAG
    - buildah manifest add $IMAGE_TAG docker://$IMAGE/arm64:$TAG
    - buildah manifest push --all $IMAGE_TAG

stages:
  - lint
  - build
  - docker
  - deploy
  - deploy-testing

lint-web:
  extends:
    - .base-frontend-cache
  stage: lint
  script:
    - cd web
    - cargo clippy --release --features ssr --features hydrate

build-web:
  extends:
    - .base-frontend-cache
  stage: build
  script:
    - cd web
    - cargo leptos build --release
    - mkdir -p $CI_PROJECT_DIR/$ARCH/crafting
    - cp $CI_PROJECT_DIR/target/release/crafting-web $CI_PROJECT_DIR/$ARCH/crafting-web
    - cp -r $CI_PROJECT_DIR/target/site $CI_PROJECT_DIR/$ARCH/crafting/pkg
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$ARCH/crafting-web
      - $CI_PROJECT_DIR/$ARCH/crafting/pkg
  parallel:
    matrix:
      - ARCH:
          - amd64
          - arm64
  tags:
    - runner-${ARCH}

build-docker-test:
  extends:
    - .base-docker-build
  stage: docker
  variables:
    NO_PUSH: yes

build-docker:
  extends:
    - .base-docker-build
  stage: docker
  variables:
    TAG: 2.0.$CI_PIPELINE_IID
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

merge-manifests:
  extends:
    - .base-merge-manifests
  variables:
    TAG: 2.0.$CI_PIPELINE_IID
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

trigger-server:
  needs:
    - job: merge-manifests
  variables:
    TAG: 2.0.$CI_PIPELINE_IID
  stage: deploy
  trigger: server-management/main-server.ulbricht.casa/crafting.creastina.art
  rules:
    - if: $CI_COMMIT_BRANCH == "main"