[package]
name = "crafting-entities"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sea-orm = { workspace = true }